# Generated by Django 4.1.4 on 2023-02-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentstandard",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curriculums",
                to="api.subject",
            ),
        ),
        migrations.AlterField(
            model_name="learningindicator",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="gender",
            field=models.CharField(
                choices=[("M", "Mixed"), ("B", "Boys"), ("G", "Girls")],
                default="M",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="visible",
            field=models.BooleanField(
                default=True,
                help_text="Tick to show that the school is visible to users",
            ),
        ),
        migrations.AlterField(
            model_name="strand",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="substrand",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
