# Generated by Django 4.1.4 on 2023-02-07 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculum",
            name="aim",
            field=models.TextField(
                default=datetime.datetime(
                    2023, 2, 7, 8, 58, 32, 630355, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lesson",
            name="number",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
