# Generated by Django 4.1.4 on 2023-03-06 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_contentstandard_id_alter_curriculum_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningindicator",
            name="content_standard",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="content_standard",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="curriculum",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="learning_indicator",
        ),
        migrations.RemoveField(
            model_name="question",
            name="curriculum",
        ),
        migrations.AddField(
            model_name="lesson",
            name="grade",
            field=models.CharField(default="B4", editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="subject",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.subject",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lesson",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="strand",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.strand",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="api.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="strand",
            name="name",
            field=models.CharField(max_length=225),
        ),
        migrations.DeleteModel(
            name="ContentStandard",
        ),
        migrations.DeleteModel(
            name="LearningIndicator",
        ),
    ]
