# Generated by Django 4.1.4 on 2023-02-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_curriculum_aim_alter_lesson_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentstandard",
            old_name="sub_strand",
            new_name="substrand",
        ),
    ]
