# Generated by Django 4.1.4 on 2023-03-07 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_learningindicator_content_standard_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="substrand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="api.substrand",
            ),
        ),
    ]
