# Generated by Django 4.1.4 on 2023-02-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_sub_strand_contentstandard_substrand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="content_standard",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="api.contentstandard",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="strand",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="api.strand",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="subject",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="api.subject",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="substrand",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="api.substrand",
            ),
        ),
    ]
