# Generated by Django 4.1.4 on 2023-02-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_lesson_content_standard_alter_lesson_strand_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="curriculum",
            unique_together={("grade", "subject")},
        ),
        migrations.RemoveField(
            model_name="curriculum",
            name="aim",
        ),
        migrations.RemoveField(
            model_name="curriculum",
            name="philosophy",
        ),
    ]
