# Generated by Django 4.1.4 on 2023-03-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_lesson_substrand"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(default="hello-world", editable=False, unique=True),
            preserve_default=False,
        ),
    ]
