# Generated by Django 4.1.4 on 2023-02-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_curriculum_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculum",
            name="id",
            field=models.CharField(
                editable=False, max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
