# Generated by Django 4.1.4 on 2023-02-10 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_school_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools_added",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
