# Generated by Django 4.1.4 on 2023-02-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_school_added_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="substrand",
        ),
        migrations.AddField(
            model_name="question",
            name="lesson",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="api.contentstandard",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="school",
            name="telephone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.telephone",
            ),
        ),
    ]
